name: Create Release on Commit

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit message
        id: get_commit_message
        run: |
          # Get the full commit message
          commit_message=$(git log -1 --pretty=%B)
          # Extract the first line for tag and release name
          tag_name=$(echo "$commit_message" | head -n 1 | tr -cd '[:alnum:].-_')
          # Extract all lines after the first for description (if any)
          description=$(echo "$commit_message" | tail -n +2 | sed '/^$/d')
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "description=$description" >> $GITHUB_ENV

      - name: Remove README.md
        run: rm -f README.md

      - name: Create zip file
        run: zip -r zapret.zip ./*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.tag_name }}"
          release_name: "${{ env.tag_name }}"
          body: "${{ env.description }}"
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./zapret.zip
          asset_name: zapret.zip
          asset_content_type: application/zip